spring:
  application:
    name: NOTIFICATION-SERVICE

  datasource:
    url: jdbc:postgresql://ep-gentle-block-aoifiomz-pooler.c-2.ap-southeast-1.aws.neon.tech/auth_db_1?sslmode=require&channel_binding=require

    username: neondb_owner
    password: npg_pW7izeTrDs3H
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: cribcareinfo@gmail.com
    password: wcuh mggi wvol hayp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8082

notification:
  token:
    expiry-ms: 120000

image:
  storage:
    root-path: C:/uploads

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ip-172-31-43-132.ap-south-1.compute.internal:8761/eureka/
  instance:
    prefer-ip-address: true