spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
    url: jdbc:postgresql://ep-lingering-moon-a1r0p1ab-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_7YOJ1gIPXCcB
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8086

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://35.154.182.218:8761/eureka/
  instance:
    prefer-ip-address: true




stripe:
  secret-key: sk_test_51T3ZqV2aKU7TLjV0KwlX24rxAvtSv04Zn7OArA3yNCU1KxC4A1XCSpgg72TuEUXn39c0rsUi1b0o9c8J6ZnNvu0e00fifWtivb
  webhook-secret:  whsec_f732ff1a17c891663f172c12286e42e2c22228d5cd07a9fb4c8b38e18313f841
  extension-price: 400   # amount in paise/cents (₹50 or $50)
  currency: usd

#  pk_test_51T3ZqV2aKU7TLjV0kFE8juIoQReCYn2HJqls1POG9IjJAodJLBNEKxEzDDAJ1AkMZqz0jXivrqA2Uj6Ovjc7uQoQ001AsCelP5




# postgresql://neondb_owner:npg_7YOJ1gIPXCcB@ep-lingering-moon-a1r0p1ab-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require