spring:
  application:
    name: INVENTORY-SERVICE
#  datasource:
#    url: jdbc:postgresql://ep-bitter-darkness-a122sbpg-pooler.ap-southeast-1.aws.neon.tech:5432/INVENTORY_SERVICE?sslmode=require
#    username: neondb_owner
#    password: npg_lkA9tfR2eHQI
#    driver-class-name: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://ep-steep-feather-aonbk9z9-pooler.c-2.ap-southeast-1.aws.neon.tech/inventory_db_1?sslmode=require
    username: neondb_owner
    password: npg_Glfkpqw0y1Hm
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8084

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ip-172-31-43-132.ap-south-1.compute.internal:8761/eureka/
  instance:
    prefer-ip-address: true

inventory:
  file:
    upload-dir: C:/InventoryUploads
